version: "3.8"

services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    expose:
      - "8000"
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - fastapi_app
    restart: always
